url: 'https://mdoliwa.com'
baseurl: '/'
title: 'Marcin Doliwa'
permalink: /:title

collections:
  notes:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
